name: Standaard Webserver
description: |
               aaaaaaaaaaaaaaaaaaaaaaaaaaaabhahfg Replicasdfsdfdfsf Set.
category: webserver
maintainer: Harm Jacob Drijfhout
license: private
version: Apache 2.4.7
